import type { Course } from "../types";

/** Demo Computer Networks course — structure + learning state for API smoke without LLM. */
export const CN_COURSE_ID = "cn-kurose";

export function createCnSeedCourse(): Course {
  return {
    id: CN_COURSE_ID,
    title: "Computer Networks",
    lifecycle: "activated",
    lastStudiedAt: "2026-07-30T18:40:00.000Z",
    createdAt: "2026-07-01T10:00:00.000Z",
    sessionDefaultMinutes: 25,
    sources: [
      {
        id: "src-1",
        name: "Kurose-Ross-ch3-transport.pdf",
        pages: 86,
        status: "ready",
        lastUsed: "2026-07-30",
      },
      {
        id: "src-2",
        name: "Lecture-05-TCP.pdf",
        pages: 42,
        status: "ready",
        lastUsed: "2026-07-29",
      },
      {
        id: "src-3",
        name: "Lecture-02-HTTP.pdf",
        pages: 28,
        status: "ready",
      },
    ],
    units: [
      {
        id: "u-intro",
        title: "Introduction & edge",
        order: 0,
        lessonIds: ["l-internet", "l-delay", "l-layers"],
      },
      {
        id: "u-app",
        title: "Application",
        order: 1,
        lessonIds: ["l-http", "l-dns", "l-smtp"],
      },
      {
        id: "u-transport",
        title: "Transport",
        order: 2,
        lessonIds: ["l-udp", "l-tcp", "l-rdt", "l-congestion"],
      },
      {
        id: "u-network",
        title: "Network",
        order: 3,
        lessonIds: ["l-ip", "l-forward", "l-routing"],
      },
      {
        id: "u-link",
        title: "Link",
        order: 4,
        lessonIds: ["l-mac", "l-ethernet", "l-switch"],
      },
    ],
    lessons: {
      "l-internet": lesson("l-internet", "u-intro", "What is the Internet?", 10, "mastered", 0.92, 40, 40, true),
      "l-delay": lesson("l-delay", "u-intro", "Delay, loss, throughput", 12, "mastered", 0.88, 280, 40, true),
      "l-layers": lesson("l-layers", "u-intro", "Protocol layers", 12, "available", 0.35, 520, 40, true),
      "l-http": lesson("l-http", "u-app", "HTTP", 14, "due", 0.55, 40, 220, true),
      "l-dns": lesson("l-dns", "u-app", "DNS", 12, "in_progress", 0.4, 280, 220, true),
      "l-smtp": lesson("l-smtp", "u-app", "SMTP / IMAP overview", 10, "locked", 0, 520, 220, false),
      "l-udp": lesson("l-udp", "u-transport", "UDP", 10, "available", 0.2, 40, 400, true),
      "l-tcp": lesson("l-tcp", "u-transport", "TCP basics", 15, "weak", 0.42, 280, 400, true),
      "l-rdt": lesson("l-rdt", "u-transport", "Reliable data transfer", 16, "locked", 0, 520, 400, false),
      "l-congestion": lesson("l-congestion", "u-transport", "TCP congestion control", 18, "due", 0.38, 760, 400, true),
      "l-ip": lesson("l-ip", "u-network", "IP addressing", 12, "locked", 0, 40, 580, false),
      "l-forward": lesson("l-forward", "u-network", "Forwarding vs routing", 12, "locked", 0, 280, 580, false),
      "l-routing": lesson("l-routing", "u-network", "Routing ideas", 14, "locked", 0, 520, 580, false),
      "l-mac": lesson("l-mac", "u-link", "Multiple access", 12, "locked", 0, 40, 760, false),
      "l-ethernet": lesson("l-ethernet", "u-link", "Ethernet / MAC", 12, "locked", 0, 280, 760, false),
      "l-switch": lesson("l-switch", "u-link", "Switches", 10, "locked", 0, 520, 760, false),
    },
  };
}

function lesson(
  id: string,
  unitId: string,
  title: string,
  estMinutes: number,
  status: Course["lessons"][string]["status"],
  mastery: number,
  x: number,
  y: number,
  quizReady: boolean,
): Course["lessons"][string] {
  return {
    id,
    unitId,
    title,
    estMinutes,
    status,
    mastery,
    objectives: [`Explain core ideas of ${title}`],
    sections: quizReady
      ? [
          {
            heading: "Overview",
            body: `${title} — demo seed content. Real RAG generation lands in Phase B3.`,
          },
        ]
      : [],
    citations: quizReady
      ? [
          {
            id: `${id}-c1`,
            sourceId: "src-1",
            sourceName: "Kurose-Ross-ch3-transport.pdf",
            page: 1,
            excerpt: "Seed citation placeholder for API smoke tests.",
          },
        ]
      : [],
    quiz: quizReady
      ? [
          {
            id: `${id}-q1`,
            stem: `Which statement best matches ${title}?`,
            options: [
              { id: "a", text: "Unrelated transport trivia" },
              { id: "b", text: "A grounded core concept from the sources" },
              { id: "c", text: "A link-layer only claim" },
              { id: "d", text: "An application-layer only claim" },
            ],
            correctOptionId: "b",
            explanation: "Demo quiz — real items generated by DeepSeek V4 Flash in B3.",
          },
        ]
      : [],
    quizReady,
    position: { x, y },
  };
}
